### ISSUE TITLE
I'm not sure why this table nil error is happening.

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [XProject/x-radiolist#3]
![image](https://user-images.githubusercontent.com/25211271/218704909-cacf30fd-255d-4770-8993-a7039c3d9996.png)

I run latest game build and artifacts.

pma-voice
tgiann-radio 

onesync infiniti

I hit connect to join the Radio channel then it gives this error

**Comment by mahanmoulaei** [comment]
Try downloading the latest version of x-radiolist which is _0.9.7_ as of now, and see if that fixes your issue.
It doesn't matter what radio you use, the only important dependency is pma-voice.
Are you using Config.UseRPName? If yes, what is your framework?

Also, it technically shouldn't really matter but rename your script to ```x-radiolist``` & remove the ```-master``` part from its name

**Comment by mahanmoulaei** [comment]
@Legacy-TacticalGamingInteractive any update?

**Comment by Legacy-TacticalGamingInteractive** [comment]
its not working with latest version 0.9.7
i havent done anything other than run it as is

**Comment by mahanmoulaei** [comment]
Are you using Config.UseRPName? If yes, what is your framework?

**Comment by Legacy-TacticalGamingInteractive** [comment]
Apologies that was my fault with Config typo.
